<a target="_blank" href="https://colab.research.google.com/github/thinh-vu/vnstock/blob/main/docs/4_funds_vnstock3.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

## Khởi tạo đối tượng

In [ ]:
!pip install vnstock3

In [3]:
from vnstock3.explorer.fmarket.fund import Fund
fund = Fund()

Total number of funds currently listed on Fmarket:  49

## Liệt kê danh sách các quỹ

In [4]:
fund.listing().head()

Total number of funds currently listed on Fmarket:  49

,short_name,name,fund_type,fund_owner_name,management_fee,inception_date,nav,nav_change_previous,nav_change_last_year,nav_change_inception,...,nav_change_3m,nav_change_6m,nav_change_12m,nav_change_24m,nav_change_36m,nav_change_36m_annualized,nav_update_at,fund_id_fmarket,fund_code,vsd_fee_id
0,SSISCA,QUỸ ĐẦU TƯ LỢI THẾ CẠNH TRANH BỀN VỮNG SSI,Quỹ cổ phiếu,CÔNG TY TNHH QUẢN LÝ QUỸ SSI,1.75,2014-09-25,40055.88,0.46,31.01,177.93,...,13.61,27.83,41.96,44.61,39.34,11.69,2024-07-09,11,SSISCA,SSISCAN001
1,VESAF,QUỸ ĐẦU TƯ CỔ PHIẾU TIẾP CẬN THỊ TRƯỜNG VINACA...,Quỹ cổ phiếu,CÔNG TY CỔ PHẦN QUẢN LÝ QUỸ VINACAPITAL,1.75,2017-04-17,31659.50,0.64,22.91,216.60,...,11.05,20.76,31.68,35.44,37.71,11.26,2024-07-09,23,VESAF,VESAFN002
2,BVPF,QUỸ ĐẦU TƯ CỔ PHIẾU TRIỂN VỌNG BẢO VIỆT,Quỹ cổ phiếu,CÔNG TY TNHH QUẢN LÝ QUỸ BẢO VIỆT,1.50,2016-12-28,20924.00,1.62,23.09,109.20,...,8.50,20.05,31.92,32.26,30.27,9.21,2024-07-09,14,BVPF,BVPFN001
3,VEOF,QUỸ ĐẦU TƯ CỔ PHIẾU HƯNG THỊNH VINACAPITAL,Quỹ cổ phiếu,CÔNG TY CỔ PHẦN QUẢN LÝ QUỸ VINACAPITAL,1.75,2014-06-30,30569.71,0.30,22.23,153.82,...,7.96,18.80,29.87,28.10,29.68,9.05,2024-07-09,20,VEOF,VEOFN003
4,VCBF-TBF,QUỸ ĐẦU TƯ CÂN BẰNG CHIẾN LƯỢC VCBF,Quỹ cân bằng,CÔNG TY LIÊN DOANH QUẢN LÝ QUỸ ĐẦU TƯ CHỨNG KH...,1.50,2013-12-23,32058.82,0.87,16.68,60.73,...,6.12,13.92,21.60,28.11,28.62,8.75,2024-07-09,31,VCBFTBF,VCBFTBFN001

## Tìm kiếm quỹ theo tên viết tắt

In [5]:
# Nhập 1 phần tên viết tắt để lọc
fund.filter('DC')

   id shortName
0  40     VNDCF
1  67      DCIP
2  62    HDBOND
3  27      DCBF
4  25      DCDE
5  28      DCDS
6  29      DCAF

## Thông tin chi tiết quỹ

### Tăng trưởng NAV

In [ ]:
fund.details.nav_report('SSISCA')

Retrieving data for SSISCA

            date  nav_per_unit short_name
0     2017-01-04      14412.31     SSISCA
1     2017-01-11      14527.86     SSISCA
2     2017-01-18      14240.04     SSISCA
3     2017-01-25      14547.21     SSISCA
4     2017-01-31      14541.96     SSISCA
...          ...           ...        ...
1535  2024-07-03      39212.58     SSISCA
1536  2024-07-04      39510.62     SSISCA
1537  2024-07-05      39690.75     SSISCA
1538  2024-07-08      39871.40     SSISCA
1539  2024-07-09      40055.88     SSISCA

[1540 rows x 3 columns]

### Danh mục đầu tư lớn (top 10)

In [6]:
fund.details.top_holding('SSISCA')

Retrieving data for SSISCA

,stock_code,industry,net_asset_percent,type_asset,update_at,fundId,short_name
0,FPT,Công nghệ và thông tin,17.10,STOCK,2024-07-05,11,SSISCA
1,MWG,Bán lẻ,6.65,STOCK,2024-07-05,11,SSISCA
2,ACB,Ngân hàng,5.77,STOCK,2024-07-05,11,SSISCA
3,HPG,Vật liệu xây dựng,3.97,STOCK,2024-07-05,11,SSISCA
4,CTG,Ngân hàng,3.64,STOCK,2024-07-05,11,SSISCA
5,STB,Ngân hàng,3.32,STOCK,2024-07-05,11,SSISCA
6,MBB,Ngân hàng,3.24,STOCK,2024-07-05,11,SSISCA
7,BWE,Tiện ích,2.97,STOCK,2024-07-05,11,SSISCA
8,REE,Xây dựng,2.95,STOCK,2024-07-05,11,SSISCA
9,DHC,Sản xuất Phụ trợ,2.75,STOCK,2024-07-05,11,SSISCA

### Phân bổ theo ngành (Top 10)

In [7]:
fund.details.industry_holding('SSISCA')

Retrieving data for SSISCA

                      industry  net_asset_percent short_name
0                    Ngân hàng              20.46     SSISCA
1       Công nghệ và thông tin              17.10     SSISCA
2                 Bất động sản               8.68     SSISCA
3                       Bán lẻ               6.73     SSISCA
4             Sản xuất Phụ trợ               4.72     SSISCA
5            Vận tải - Kho bãi               4.62     SSISCA
6            Vật liệu xây dựng               3.97     SSISCA
7                     Tiện ích               2.97     SSISCA
8                     Xây dựng               2.95     SSISCA
9       Sản xuất Hàng gia dụng               2.24     SSISCA
10           Chế biến thủy sản               1.85     SSISCA
11  Sản xuất Thiết bị, máy móc               1.82     SSISCA
12    Sản xuất Nhựa - Hóa chất               1.73     SSISCA
13      Dịch vụ tư vấn, hỗ trợ               1.70     SSISCA
14                 Chứng khoán               1.52     SSISCA

### Phân bổ theo tài sản

In [11]:
fund.details.asset_holding('SSISCA')

Retrieving data for SSISCA

   asset_percent                asset_type short_name
0          83.08                  Cổ phiếu     SSISCA
1          16.92  Tiền và tương đương tiền     SSISCA